config/routes.rb
Rails.application.routes.draw do

  resources :matches, only: :index do
    match 'advanced_search' => 'matches#advanced_search',
          on: :collection, via: [:get, :post], as: :advanced_search
  end
  root to: 'matches#index'

end

app/models/match.rb
class Match < ActiveRecord::Base
  belongs_to :winner, class_name: 'Player'
  belongs_to :loser, class_name: 'Player'
end

app/models/player.rb
class Player < ActiveRecord::Base
  has_many :wins, class_name: 'Match', foreign_key: 'winner_id'
  has_many :losses, class_name: 'Match', foreign_key: 'loser_id'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  respond_to :html

  def index
    @search = Match.ransack(params[:q])
    #@matches  = params[:distinct].to_i.zero? ?
      #@search.result :
      #@search.result(distinct: true)

    @matches = @search.result.paginate(page: params[:page], per_page: params[:per_page])
    #@total_entries = @matches.size
    # will_paginate requires total_entries for total results, size will only give batch/page size
    @total_entries = @matches.total_entries
    respond_with @matches
  end

  # for some reason advanced search does not save the params q upon pagination,
  # so i have to save it to session. Which means that a CLEAR may be requried.
  def advanced_search

    # if there is a no value then take it to session
    if !params[:q]
      params[:q] = session[:query]
    end
    @search = Match.ransack(params[:q])
    @search.build_grouping unless @search.groupings.any?
    @matches = @search.result.paginate(page: params[:page], per_page: params[:per_page])
    @total_entries = @matches.total_entries
    if params[:q]
      session[:query] = params[:q]
    end
    #puts "saving @paramsq to session"
    #pp session[:query]

    #@matches  = params[:distinct].to_i.zero? ?
      #@search.result :
      #@search.result(distinct: true)

    respond_with @matches
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def setup_search_form(builder)
    fields = builder.grouping_fields builder.object.new_grouping,
      object_name: 'new_object_name', child_index: "new_grouping" do |f|
      render('grouping_fields', f: f)
    end
    content_for :document_ready, %Q{
      var search = new Search({grouping: "#{escape_javascript(fields)}"});
      $(document).on("click", "button.add_fields", function() {
        search.add_fields(this, $(this).data('fieldType'), $(this).data('content'));
        return false;
      });
      $(document).on("click", "button.remove_fields", function() {
        search.remove_fields(this);
        return false;
      });
      $(document).on("click", "button.nest_fields", function() {
        search.nest_fields(this, $(this).data('fieldType'));
        return false;
      });
    }.html_safe
  end

  def button_to_remove_fields(name, f)
    content_tag :button, name, class: 'remove_fields'
  end

  def button_to_add_fields(name, f, type)
    new_object = f.object.send "build_#{type}"
    fields = f.send("#{type}_fields", new_object, child_index: "new_#{type}") do |builder|
      render(type.to_s + "_fields", f: builder)
    end
    content_tag :button, name, :class => 'add_fields', 'data-field-type' => type, 'data-content' => "#{fields}"
  end

  def button_to_nest_fields(name, type)
    content_tag :button, name, :class => 'nest_fields', 'data-field-type' => type
  end
end

app/helpers/matches_helper.rb
module MatchesHelper
  def matches_model_fields
    # which fields to display and sort by
    [:tourney_id, :tourney_name, :tourney_date, :winner_name, :loser_name, :score, :surface, :round]
  end

  def matches_results_limit
    # max number of search results to display
    10
  end

  def matches_display_query_sql(users)
    "SQL: #{users.to_sql}"
  end

  def matches_display_results_header(count)
    if count > matches_results_limit
      "Your first #{matches_results_limit} results out of #{count} total"
    else
      "Your #{pluralize(count, 'result')}"
    end
  end

  def action
    action_name == 'advanced_search' ? :post : :get
  end

  def matches_display_sort_column_headers(search)
    i = 0
    matches_model_fields.each_with_object('') do |field, string|
      if i == 0
        string << content_tag(:th, '#')
      end
      i+= 1
      string << content_tag(:th, sort_link(search, field, {}, method: action))
    end
  end

  def matches_display_search_results(objects)
    offset = objects.offset
    i = 1
    #objects.limit(results_limit).each_with_object('') do |object, string|
    objects.each_with_object('') do |object, string|
      string << content_tag(:tr, matches_display_search_results_row(object, offset + i))
      i += 1
    end
  end

  def matches_display_search_results_row(object, offset)
    flag = true
    matches_model_fields.each_with_object('') do |field, string|
      if flag
        string << content_tag(:td, offset)
        flag = false
      end
      string << content_tag(:td, object.send(field))
    end
    .html_safe
  end

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="well well-sm">
        Ruby on Rails v4.2.7. The data is courtesy <a href="https://github.com/JeffSackmann/tennis_atp">Jeff Sackman</a> and is only for the period 2000 to Feb 2016 (due to heroku limitations). The data only contains matches of the top ranked players.
      </div>
      <nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <a class="navbar-brand" href="#">TennisQuery</a>
          </div>
          <ul class="nav navbar-nav">
            <li class="active"><a href="#">Home</a></li>
            <li><a href="http://www.atpworldtour.com/en/rankings/singles">ATP Rankings</a></li>
            <li><a href="http://tt.tennis-warehouse.com/">Talk Tennis</a></li> 
            <li><a href="http://www.atpworldtour.com/en/scores/current/">Scores</a></li> 
          </ul>
        </div>
      </nav>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Match Point</title>
  <%= stylesheet_link_tag "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <script type="text/javascript">
    $(function() {
      <%= yield :document_ready %>
    });
  </script>

</head>

<body>
  <%#= render 'layouts/header' %>
  <div class="container">
    <% flash.each do | message_type, message | %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %> 
    <%= render 'layouts/footer' %>
    <%#= debug(params) if Rails.env.development? %>
  </div>
</body>
</html>

app/views/matches/_attribute_fields.erb
<%= content_tag(:span, f.attribute_select(associations: %w(posts comments)),
  { class: 'fields', 'data-object-name' => f.object_name }, false) %>

app/views/matches/_condition_fields.erb
<%= content_tag :fieldset, {
  class: 'fields condition', 'data-object-name' => f.object_name
  } do %>

  <%= content_tag(:legend, button_to_remove_fields('remove', f),
    nil, false) %>

  <%= f.attribute_fields do |a| %>
    <%= render 'attribute_fields', f: a %>
  <% end %>

  <%= f.predicate_select %>

  <%= f.value_fields do |v| %>
    <%= render 'value_fields', f: v %>
  <% end %>

  <%= button_to_add_fields 'Add Value', f, :value %>

<% end %>

app/views/matches/_grouping_fields.erb
<%= content_tag :fieldset, { class: 'fields',
  'data-object-name' => f.object_name } do %>

  <%= content_tag(:legend, "Match #{f.combinator_select} conditions #{
    button_to_remove_fields 'remove', f}", nil, false) %>

  <%= f.condition_fields do |c| %>
    <%= render 'condition_fields', f: c %>
  <% end %>

  <%= button_to_add_fields 'Add Condition', f, :condition %>

  <%= f.grouping_fields do |g| %>
    <%= render 'grouping_fields', f: g %>
  <% end %>

  <%= button_to_nest_fields 'Add Condition Group', :grouping %>

<% end %>

app/views/matches/_results.html.erb
<%#= content_tag :h2, matches_display_results_header(@matches.size) %>
<%= will_paginate @matches %>
<%= content_tag :h3,  page_entries_info(@matches)  %>
<%= content_tag(:table, class: "table table-bordered") do %>
  <%= content_tag :thead, matches_display_sort_column_headers(@search), nil, false %>
  <%= content_tag :tbody, matches_display_search_results(@matches), nil, false %>
<% end %>
<%= will_paginate @matches %>
<% if Rails.env.development? %>
<%= content_tag :p, matches_display_query_sql(@matches) %>
<% end %>

app/views/matches/_sort_fields.erb
<%= content_tag(:span,
  "#{f.sort_select} #{button_to_remove_fields('remove', f)}",
  { class: 'fields', 'data-object-name' => f.object_name }, false) %>

app/views/matches/_value_fields.erb
<%= content_tag(:span, f.text_field(:value),
  { class: 'fields value', 'data-object-name' => f.object_name }, false) %>

app/views/matches/advanced_search.html.erb
<h1>Advanced Match Search</h1>
<%= link_to 'Simple mode', matches_path %>

<%= search_form_for(
  @search,
  url: advanced_search_matches_path,
  html: { method: :post }
  ) do |f| %>

  <% setup_search_form f %>

  <fieldset >
    <legend>Sorting</legend>
    <%= f.sort_fields do |s| %>
      <%= render 'sort_fields', f: s %>
    <% end %>
    <%= button_to_add_fields "Add Sort", f, :sort %>
  </fieldset>

  <fieldset>
    <legend>Condition Groups</legend>
    <%= f.grouping_fields do |g| %>
      <%= render 'grouping_fields', f: g %>
    <% end %>
    <%= button_to_add_fields "Add Condition Group", f, :grouping %>
  </fieldset>

  <%#= label_tag :distinct, 'Return distinct records?' %>
  <%#= check_box_tag :distinct, '1', params[:distinct].to_i == 1 %>
  <%#= f.submit %>
  <%= f.submit "Search", class: "btn btn-primary btn-block" %>
<% end %>

<%= render 'results' %>

app/views/matches/index.html.erb
<h1>Tennis Query</h1>
<%= link_to 'Goto Advanced mode', advanced_search_matches_path %>

<%= search_form_for @search  do |f| %>
  <fieldset>
    <legend>Player</legend>
        <%= f.label :winner_name_or_loser_name_cont, "Name contains", class: 'control-label col-sm-3' %>
        <div class="col-sm-8">
        <%= f.text_field :winner_name_or_loser_name_cont, placeholder: 'Winner or loser name contains ...', class: 'form-control'  %>
        </div>
        <%= f.label :winner_name_cont, "Winner", class: ' col-sm-3' %>
        <div class="col-sm-3">
        <%= f.text_field :winner_name_cont, placeholder: 'Winner name contains', class: ' '  %>
        </div>
        <%= f.label :loser_name_cont, "Loser", class: ' col-sm-3' %>
        <div class="col-sm-3">
        <%= f.text_field :loser_name_cont, placeholder: 'Loser name contains', class: ' '  %>
        </div>
  </fieldset>

  <fieldset>
    <legend>Event</legend>
    <div class="row">
        <%= f.label :tourney_name_cont, class: 'control-label col-sm-3' %>
        <div class="col-sm-3">
        <%= f.text_field :tourney_name_cont , class: 'form-control' %>
        </div>
        <%= f.label :tourney_date_start, class: 'control-label col-sm-3' %>
        <div class="col-sm-3">
        <%= f.text_field :tourney_date_start , class: 'form-control' %>
        </div>
    </div>
    <div class="row">
        <%= f.label :surface_eq, "Surface", class: 'control-label col-sm-3' %>
        <div class="col-sm-3">
        <%= f.text_field :surface_eq , placeholder: 'Clay/ Hard/ Grass/ Carpet', class: 'form-control' %>
        </div>
        <%= f.label :tourney_level_eq, "Tourney level (G/M/A/D)", class: 'control-label col-sm-3' %>
        <div class="col-sm-3">
        <%= f.text_field :tourney_level_eq , class: 'form-control' %>
        </div>
    </div>
  </fieldset>

  <%#= label_tag :distinct, 'Return distinct records?' %>
  <%#= check_box_tag :distinct, '1', params[:distinct].to_i == 1 %>
  <%= f.submit "Search", class: "btn btn-primary btn-block" %>
<% end %>
<%#= will_paginate %>
<%= render 'results' %>
<%#= will_paginate %>

app/views/matches/show.html.erb
<h1>Matches#show</h1>
<p>Find me in app/views/matches/show.html.erb</p>